public class Orientada {
	
	public static void main(String[] args) {
		/* POO É UM PARADIGMA DE PROGRAMAÇÃO
		 * MODULARIZAÇÃO É ONDE POO BRILHA
		 * DIVIDIR VÁRIAS FUNCIONALIDADES
		 * POO FOCA EM REUTILIZAÇÃO
		 * MODELO DE IMPLEMENTAÇÃO , VULGO CLASSE
		 * FUNCIONA COMO UM PROJETO
		 * UML BASICAMENTE UM PROJETO DO QUE RELACIONA OS MÉTODOS
		 * ATRIBUTOS -> VARIÁVEIS
		 * METODOS -> FUNÇÕES
		 * OBJETOS -> PRECISAM DE UM NOME, ATRIBUTOS DELE(METÓDO, É O QUE MANIPULAM ELE),
		 * MÉTODOS INFLUENCIAM NOS ATRIBUTOS
		 * ATRIBUTOS SÃO CARACTERISTICAS DO OBJETO
		 * ONDE TEMOS UMA AÇÃO É MÉTODO
		 * TODA VEZ QUE TEMOS UMA CARACTERÍSTICA DE AÇÃO É ATRIBUTO
		 * 
		 * NOME: BOLA
		 * ATRIBUTOS: POSIÇÃO, MODALIDADE, PESO, MATERIAL, MARCA, FABRICACAO
		 * METODOS : MOVIMENTAR, QUICAR, MURCHAR, ENCHER
		 * 
		 * NOME : CARRO POR AUTOMÓVEL( DEIXAR MAIS GENÉRICO)
		 * ATRIBUTOS : COR, MARCA, POTÊNCIA, MODALIDADE, NUM RODAS
		 * MÉTODOS : ACELERAR, FREAR, EMBREAGEM, TROCAR PNEU
		 * 
		 * NOME : CASA POR RESIDÊNCIA (MAIS GENÉRICO)
		 * ATRIBUTOS : NUMERO DE QUARTOS, COR, ANDARES, LOCALIZAÇÃO
		 * MÉTODOS : ABRIR PORTAS, REFORMAR,  DEMOLIR, LIMPAR
		 * 
		 * NOME : COMPUTADOR POR
		 * ATRIBUTOS : CPU, GPU, MEMORIA. TAMANHO
		 * MÉTODOS : LIGAR, DESLIGAR , EXPLODIR
		 * 
		 * NOME : EMBARCAÇÃO
		 * ATRIBUTOS : TAMANHO, CALADO, TIPO
		 * MÉTODOS : ACELERAR, FREAR, EXPLODIR
		 * 
		 * NOME : AERONAVE
		 * ATRIBUOS : COR, PESO, TIPO, QNT MOTORES, TIPO PROPULSÃO
		 * MÉTODOS : DECOLAR, POUSAR, EXPLODIR, 
		 * 
		 * CLASSES MAIS GENÉRICAS POSSÍVEL PARA NO FINAL SER ALGO ESPECÍFICO
		 * CLASSES PODEM DEPENDER DE OUTROS OBJETOS
		 * 
		 * OBJECT É PAI DE TUDO, O FILHO JOGA FLECHA NO PAI OBJECT <- FILHO
		 * 
		 * 
		 * 
		 * */
		
		
		
	}
	
	
}